name: 'Update submodules'

on:
  workflow_call:
    secrets:
      SUBMODULE_UPDATE:
        required: true

jobs:
  sync:
    name: 'Update submodules'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.SUBMODULE_UPDATE }}
        submodules: true

    # Update references
    - name: Git submodule update
      run: |
        git pull --recurse-submodules
        git submodule update --remote

    - name: Commit update
      run: |
        set -eu
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        if ! git diff --quiet; then
          git commit -a -m "Update submodules" -m "$(git submodule summary)"
          git push
        else
           echo "No changes to commit"
        fi
